#!/bin/bash
# setup-local-dev.sh — Развёртывание локального dev-окружения
#
# Что делает:
#   1. Запускает PostgreSQL + Redis через Docker
#   2. Ждёт готовности сервисов
#   3. Применяет базовую схему + все миграции
#   4. Создаёт .env для локальной разработки
#   5. Устанавливает Python зависимости
#
# Usage:
#   cd ocpp-rp && ./tools/setup-local-dev.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BACKEND_DIR="$PROJECT_DIR/backend"

# Цвета
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${CYAN}=========================================="
echo " RedPetroleum — Local Dev Environment Setup"
echo -e "==========================================${NC}"
echo ""

# ============================================================================
# 1. Docker Compose
# ============================================================================

echo -e "${YELLOW}[1/5] Запуск PostgreSQL + Redis через Docker...${NC}"

cd "$PROJECT_DIR"

# Остановить предыдущие контейнеры если есть
docker compose -f docker-compose.dev.yml down 2>/dev/null || true

# Запустить
docker compose -f docker-compose.dev.yml up -d

echo "Ожидание готовности PostgreSQL..."
for i in $(seq 1 30); do
    if docker compose -f docker-compose.dev.yml exec -T postgres-dev pg_isready -U evpower >/dev/null 2>&1; then
        echo -e "${GREEN}  PostgreSQL готов!${NC}"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo -e "${RED}  PostgreSQL не готов за 30 секунд!${NC}"
        exit 1
    fi
    sleep 1
done

echo "Ожидание готовности Redis..."
for i in $(seq 1 15); do
    if docker compose -f docker-compose.dev.yml exec -T redis-dev redis-cli ping >/dev/null 2>&1; then
        echo -e "${GREEN}  Redis готов!${NC}"
        break
    fi
    if [ "$i" -eq 15 ]; then
        echo -e "${RED}  Redis не готов за 15 секунд!${NC}"
        exit 1
    fi
    sleep 1
done

echo ""

# ============================================================================
# 2. Database Schema
# ============================================================================

echo -e "${YELLOW}[2/5] Применение схемы БД...${NC}"

PG_HOST=localhost
PG_PORT=5433
PG_USER=evpower
PG_DB=evpower
export PGPASSWORD=evpower_dev_123

# Базовая схема
echo "  -> 000_base_schema_local.sql"
psql -h $PG_HOST -p $PG_PORT -U $PG_USER -d $PG_DB -f "$BACKEND_DIR/sql/000_base_schema_local.sql" -q 2>&1 | tail -1

# Применяем миграции по порядку (IF NOT EXISTS защитит от дублирования)
for migration in "$BACKEND_DIR"/sql/[0-9][0-9][1-9]*.sql; do
    if [ -f "$migration" ]; then
        name=$(basename "$migration")
        echo "  -> $name"
        psql -h $PG_HOST -p $PG_PORT -U $PG_USER -d $PG_DB -f "$migration" -q 2>&1 | grep -v "NOTICE" | head -3 || true
    fi
done

unset PGPASSWORD
echo -e "${GREEN}  Схема применена!${NC}"
echo ""

# ============================================================================
# 3. .env file
# ============================================================================

echo -e "${YELLOW}[3/5] Создание .env для локальной разработки...${NC}"

ENV_FILE="$BACKEND_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    echo -e "  ${YELLOW}.env уже существует — пропускаю (бэкап: .env.bak)${NC}"
    cp "$ENV_FILE" "$ENV_FILE.bak"
else
    cat > "$ENV_FILE" << 'ENVEOF'
# RedPetroleum Local Development Environment
# Auto-generated by setup-local-dev.sh

# Database (local PostgreSQL via Docker)
DATABASE_URL=postgresql://evpower:evpower_dev_123@localhost:5433/evpower

# Redis (local via Docker)
REDIS_URL=redis://localhost:6380/0

# App
APP_ENV=development
APP_PORT=9210
LOG_LEVEL=DEBUG
ENABLE_SWAGGER=true

# Security (dev only - NOT for production!)
SUPABASE_JWT_SECRET=dev-jwt-secret-not-for-production
CLIENT_FALLBACK_SECRET=dev-fallback-secret
SECRET_KEY=dev-secret-key-not-for-production
VERIFY_STATION_API_KEYS=false

# CORS (dev)
CORS_ORIGINS=http://localhost:3000,http://localhost:9210

# Payment (disabled for local testing)
PAYMENT_PROVIDER=ODENGI
ODENGI_MERCHANT_ID=test-merchant
ODENGI_PASSWORD=test-password
ODENGI_USE_PRODUCTION=false

# Push (disabled)
PUSH_NOTIFICATIONS_ENABLED=false

# OTP (dev - print to console)
OTP_CODE_LENGTH=6
OTP_TTL_SECONDS=300
ENVEOF

    echo -e "${GREEN}  .env создан!${NC}"
fi
echo ""

# ============================================================================
# 4. Python venv + dependencies
# ============================================================================

echo -e "${YELLOW}[4/5] Проверка Python зависимостей...${NC}"

cd "$BACKEND_DIR"

if [ ! -d "venv" ] && [ ! -d ".venv" ]; then
    echo "  Создание venv..."
    python3 -m venv venv
    echo "  Установка зависимостей..."
    ./venv/bin/pip install -q -r requirements.txt 2>&1 | tail -3
    echo -e "${GREEN}  venv создан и зависимости установлены!${NC}"
else
    VENV_DIR=$([ -d "venv" ] && echo "venv" || echo ".venv")
    echo -e "  ${CYAN}venv уже существует ($VENV_DIR)${NC}"
    echo "  Обновление зависимостей..."
    ./$VENV_DIR/bin/pip install -q -r requirements.txt 2>&1 | tail -3 || true
fi
echo ""

# ============================================================================
# 5. Verification
# ============================================================================

echo -e "${YELLOW}[5/5] Проверка...${NC}"

# Проверяем что тестовые данные на месте
export PGPASSWORD=evpower_dev_123
STATION_COUNT=$(psql -h $PG_HOST -p $PG_PORT -U $PG_USER -d $PG_DB -t -c "SELECT COUNT(*) FROM stations;" 2>/dev/null | tr -d ' ')
CLIENT_COUNT=$(psql -h $PG_HOST -p $PG_PORT -U $PG_USER -d $PG_DB -t -c "SELECT COUNT(*) FROM clients;" 2>/dev/null | tr -d ' ')
unset PGPASSWORD

echo "  Stations: $STATION_COUNT"
echo "  Clients: $CLIENT_COUNT"

echo ""
echo -e "${GREEN}=========================================="
echo " Setup complete!"
echo "=========================================="
echo -e "${NC}"
echo "Для запуска backend:"
echo "  cd backend"
echo "  source venv/bin/activate  # или .venv/bin/activate"
echo "  uvicorn app.main:app --host 0.0.0.0 --port 9210 --reload"
echo ""
echo "Для запуска симулятора (в другом терминале):"
echo "  ./tools/test-ocpp.sh 16 SIM-TEST"
echo ""
echo "Для E2E теста (в третьем терминале):"
echo "  ./tools/test-charging-flow.sh 16"
echo ""
echo "PostgreSQL: localhost:5433 (evpower/evpower_dev_123)"
echo "Redis:      localhost:6380"
echo "Backend:    http://localhost:9210"
echo "Swagger:    http://localhost:9210/docs"
